# Generated by Django 5.1.4 on 2025-01-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('students', models.ManyToManyField(related_name='courses', to='students.student', verbose_name='Enrolled Students')),
            ],
        ),
    ]
